accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("logout/", views.logout_view, name="logout"),
    path("login/", views.login_view, name="login"),
    path("register/", views.registration_view, name="register"),
    path("leaderboard/", views.leaderboard_view, name="leaderboard"),
    path("<str:username>/follow/", views.follow_view, name="follow"),
]

chats/urls.py
# chats/urls.py
from django.urls import path

from . import views

app_name = "chats"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("room/", views.room, name="room"),
]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from accounts.views import home
from chats import views
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import (
    profile_view,
    like_view,
    quiz_score_view,
    user_enter_quiz,
    edit_profile_view,
    delete_post_view,
    quiz_view,
    post_comment,
    clear_view,
    submit_post_view,
    # search_bar,
    drop_box,
)

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("", home, name="home"),
    path("", include("accounts.urls")),
    path("", include("chats.urls")),
    path("<str:username>/", profile_view, name="profile"),
    path("<str:username>/edit_profile/", edit_profile_view, name="edit_profile"),
    path("like", like_view, name="like"),
    path("post_comment", post_comment, name="post_comment"),
    path("quiz", quiz_view, name="quiz_view"),
    path("quiz_score", quiz_score_view, name="quiz_score"),
    path("user_enter_quiz", user_enter_quiz, name="user_enter_quiz"),
    path("<str:post_id>/delete/", delete_post_view, name="delete"),
    path("<str:post_id>/clear/", clear_view, name="clear"),
    path("submit_post", submit_post_view, name="submit_post"),
    # path("search_bar", search_bar, name="search_bar"),
    path("drop_box", drop_box, name="drop_box"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings
from PIL import Image

# Create your models here.

User = settings.AUTH_USER_MODEL

class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user


class Account(AbstractBaseUser):
	email = models.EmailField(verbose_name="email", max_length=60, unique=True)
	username = models.CharField(max_length=30, unique=True)
	coins = models.DecimalField(default=0, decimal_places=3, max_digits=8)
	profile_image = models.ImageField(upload_to='profile_images', default='profile_images/default.jpg', null=True, blank=True)
	followers = models.ManyToManyField(User, blank=True, related_name='_follow')
	following = models.ManyToManyField(User, blank=True, related_name='_following')
	dms = models.ManyToManyField(User, blank=True, verbose_name='dms')
	date_joined	= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
	is_admin = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)
	is_staff = models.BooleanField(default=False)
	is_superuser = models.BooleanField(default=False)


	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username']

	objects = MyAccountManager()

	def __str__(self):
		return self.username

	# For checking permissions. to keep it simple all admin have ALL permissons
	def has_perm(self, perm, obj=None):
		return self.is_admin

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
	def has_module_perms(self, app_label):
		return True


class Post(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	caption = models.CharField(max_length=140)
	image = models.ImageField(upload_to='feed_images', null=True, blank=True, verbose_name='image')
	likes = models.ManyToManyField(User, related_name='likes', blank=True, verbose_name='likes')
	question = models.CharField(max_length=50)
	option1 = models.CharField(max_length=50)
	option2 = models.CharField(max_length=50)
	option3 = models.CharField(max_length=50)
	correct_answer = models.CharField(max_length=50)
	users_did_quiz = models.ManyToManyField(User, default=None, blank=True, related_name="users_did_quiz")
	users_right = models.ManyToManyField(User, default=None, blank=True, related_name="users_right")

	def __str__(self):
		return self.caption

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)
		img = Image.open(self.image.path)

	@property
	def total_likes(self):
		return self.likes.all().count()

	@property
	def total_comments(self):
		return self.comments.all()

class Coin(models.Model):
	network_coins = models.DecimalField(default=1000, decimal_places=3, max_digits=8)

	def __str__(self):
		network_coins = 'network coins'
		return network_coins

class Comment(models.Model):
	post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
	body = models.TextField()

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Account, Post


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        max_length=60, help_text='Required. Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'username', 'password1',
                  'password2', 'profile_image')


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(
        max_length=60, help_text='Required. Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'username', 'profile_image')


class AccountAuthenticationForm(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError(
                    'Either email or password is incorrect.')

accounts/views.py
try:
    from django.utils import simplejson as json
except ImportError:
    import json

from django.db.models import Model

from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import TemplateView

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from django.http import HttpResponse, JsonResponse

from .models import Account, Post, Coin

from accounts.forms import (
    RegistrationForm,
    AccountAuthenticationForm,
    PostForm,
    UserUpdateForm,
)

# Create your views here.

# User Registers Requests
def registration_view(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST, request.FILES)
        if form is not None:
            form.save()
            email = form.cleaned_data.get("email")
            raw_password = form.cleaned_data.get("password1")
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return redirect("home")
        else:
            context["registration_form"] = form
    else:
        form = RegistrationForm()
        context["registration_form"] = form
    return render(request, "registration/register.html", context)


def login_view(request):
    context = {}

    user = request.user
    if user.is_authenticated:
        return redirect("home")

    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST["email"]
            password = request.POST["password"]
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect("home")
    else:
        form = AccountAuthenticationForm()

    context["login_form"] = form
    return render(request, "registration/login.html", context)


def logout_view(request):
    logout(request)
    return redirect("accounts:login")


@login_required
def home(request):
    context = {}
    all_posts = Post.objects.all().order_by("-id")
    context["all_posts"] = all_posts
    return render(request, "home.html", context)


@login_required
def submit_post_view(request):
    context = {}
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return HttpResponseRedirect("/")
        else:
            form = PostForm()

        context["post_form"] = form

    return render(request, "submit_post.html", context)


@login_required
def leaderboard_view(request):
    context = {}
    users = Account.objects.all().order_by("-coins")
    context["users"] = users
    return render(request, "leaderboard.html", context)


@login_required
def profile_view(request, username):

    if username is not None:
        profile_user = Account.objects.filter(username=username).first()

        all_posts = Post.objects.all()
        all_posts = reversed(all_posts)
        users_posts = []
        user_total_posts = 0
        for post in all_posts:
            if profile_user == post.author:
                users_posts.append(post)
                user_total_posts = len(users_posts)

    else:
        profile_user = None

    context = {
        "profile_user": profile_user,
        "all_posts": users_posts,
        "user_total_posts": user_total_posts,
    }
    return render(request, "profile.html", context)


@login_required
def edit_profile_view(request, username):
    context = {}
    default_profile_image = "profile_images/default.jpg"

    if request.method == "POST":
        update_form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        if update_form.is_valid():
            if request.user.profile_image == None:
                instance = Account.objects.filter(username=request.user)
                instance.save()
            else:
                update_form.save()
            return HttpResponseRedirect("/")

    else:
        update_form = UserUpdateForm(instance=request.user)

    context["update_form"] = update_form
    return render(request, "edit_profile.html", context)


@login_required
def like_view(request):
    if request.method == "POST":
        post_id = request.POST.get("post_id")
        post = Post.objects.get(id=post_id)
        if request.user in post.likes.all():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        total_likes = post.total_likes

        context = {"total_likes": total_likes}
        return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
def follow_view(request, username):
    profile_user = Account.objects.filter(username=username).first()
    follow_logic = request.POST.get("follow_logic")

    if follow_logic == "Follow":
        follow = profile_user.followers.add(request.user)
        following = request.user.following.add(profile_user)
    else:
        unfollower = profile_user.followers.remove(request.user)
        unfollowing = request.user.following.remove(profile_user)

    followers = profile_user.followers.count()

    context = {
        "followers": followers,
        "follow_logic": follow_logic,
    }
    return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
def delete_post_view(request, post_id):
    post_id = Post.objects.all().filter(id=post_id)
    post_id.delete()
    return HttpResponseRedirect("/")


@login_required
def quiz_view(request):
    if request.method == "POST":
        post_id = request.POST.get("post_id")
        post = Post.objects.get(id=post_id)

        question = post.question
        option1 = post.option1
        option2 = post.option2
        option3 = post.option3
        correct_answer = post.correct_answer
        context = {
            "question": question,
            "option1": option1,
            "option2": option2,
            "option3": option3,
            "correct_answer": correct_answer,
        }
        return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
def quiz_score_view(request):
    if request.method == "POST":
        user = request.user
        post_id = request.POST.get("post_id")
        post = Post.objects.get(id=post_id)
        author = post.author
        user_choice = request.POST.get("quiz_option")
        correct_answer = post.correct_answer

        if user_choice == correct_answer:
            post.users_right.add(user)
            users_that_did_quiz = post.users_did_quiz.count()
            users_right_answer = post.users_right.count()
            coins = Coin.objects.get(id=1)
            total_coins = coins.network_coins

            total_coins = float(total_coins)
            coins_to_user = coins_user_get(
                users_that_did_quiz, users_right_answer, total_coins
            )
            coins_to_quiz_maker = coins_to_user * 0.05
            coins_to_user = coins_to_user - coins_to_quiz_maker
            account_of_user = Account.objects.get(username=user)
            account_of_quiz_maker = Account.objects.get(username=author)
            user_coins = float(account_of_user.coins)
            user_coins += coins_to_user
            account_of_user.coins = str(user_coins)
            account_of_user.save()
            author_coins = float(account_of_quiz_maker.coins)
            author_coins += coins_to_quiz_maker
            account_of_quiz_maker.coins = str(author_coins)
            account_of_quiz_maker.save()
            total_coins = total_coins - coins_to_user + coins_to_quiz_maker
            total_coins = str(total_coins)
            coins.network_coins = total_coins
            coins.save()
            user_right = True

        else:
            user_right = False
            coins_to_user = 0

        context = {
            "user_right": user_right,
            "coins_to_user": round(coins_to_user, 7),
        }

        return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
def user_enter_quiz(request):
    if request.method == "POST":
        user = request.user
        post_id = request.POST.get("post_id")
        post = Post.objects.get(id=post_id)
        post.users_did_quiz.add(user)
        context = {}
        return HttpResponse(json.dumps(context), content_type="application/json")

@login_required
def post_comment(request):
    if request.method == "POST":
        print("puto")
        user = request.user
        comment = request.POST.get("comment")
        post_id = request.POST.get("post_id")
        post = Post.objects.get(id=post_id)
     
        post.comments.add()

        total_comments = post.total_comments

        context = {"total_comments": total_comments}

        return HttpResponse(json.dumps(context), content_type="application/json")

@login_required
def clear_view(request, post_id):
    post = Post.objects.get(id=post_id)
    post.users_did_quiz.all().delete()
    return HttpResponseRedirect("/")


def coins_user_get(users_that_did_quiz, users_right_answer, total_coins):
    coins_to_user = (users_that_did_quiz / users_right_answer) / total_coins
    return coins_to_user

# @login_required
# def search_bar(request):
#     context = {"username": None}
#     if request.method == "POST":
#         username = request.POST.get("search_data")

#         for account in Account.objects.all():
#             if username == str(account):
#                 context["username"] = username

#         return HttpResponse(json.dumps(context), content_type="application/json")

@login_required

accounts/templates/edit_profile.html
{% extends 'base.html' %} {% block content %}
<style>
  * {
    font-family: "Rubik", sans-serif;
  }

  body {
    background: linear-gradient(-45deg, #00fff2, #2a62ff, #973dfd, #ffc400);

    background-size: 200% 200%;
    animation: gradient 8s ease infinite;
    display: flex;
    height: 100vh;
    align-items: center;
  }
  .container {
    margin-top: -80px;
    max-width: 700px;
    width: min(300px, 70%);
    padding: 25px 30px;
    background: #fff;
    border-radius: 5px;
    min-height: 100%;
    align-content: center;
  }
  .container .register {
    font-size: 20px;
    font-weight: 500;
    position: relative;
  }

  .container .register::before {
    content: "";
    position: absolute;
    height: 3px;
    width: 30px;
    /* background: linear-gradient(-45deg, #00adb3, #0052e9, #001f58); */
  }

  .container form .user-details {
    display: flex;
    margin: 0 auto;
    /* justify-content: space-between; */
    margin-top: 2px;
    margin-bottom: 2px;
  }
  form .user-details .form-floating mb-3 {
    width: calc(100% / 2 - 20px);
  }

  form .user-details .form-floating mb-3 input {
    height: 45px;
    width: 70%;
    border-radius: 5px;
  }

  form .button {
    height: 45px;
    margin: 45px 0;
    margin-top: 2px;
    transition: 0.5s all;
    border-radius: 5px;
    cursor: pointer;
    background-color: #973dfd;
  }
  form .button input {
    height: 100%;
    width: 100%;
    outline: none;
    color: #fff;
    border: none;
    font-size: 500;
    font-weight: 500;
    letter-spacing: 1px;
    margin-top: 0%;
    border-radius: 5px;
    transition: 0.5s;
  }
  /* form .button:hover{
    background: linear-gradient(-45deg, #00adb3, #003aa7, #703dfd, #FFC947);
    
  } */
  .form__input {
    font-family: "Rubik", sans-serif;
    padding-bottom: 1px;
    padding-right: 50px;
    padding-left: 5px;
    background-color: rgb(243, 243, 243);
    font-size: 15px;
    border-color: rgb(251, 252, 252);
    border: 1px;
    border-radius: 2px;
    margin-bottom: 10px;
    display: flex;
    flex: 1;
    width: 100%;
  }

  .submit_picture {
    margin-bottom: 0px;
    padding: 0%;
  }

  @keyframes gradient {
    0% {
      background-position: 0% 50%;
    }
    50% {
      background-position: 80% 40%;
    }
    100% {
      background-position: 0% 50%;
    }
  }

  h1 {
    color: black;
    display: flex;
  }

  .neuraltrain {
    font-family: "Rubik", sans-serif;
  }

  h3 {
    color: black;
  }
  h4 {
    color: black;
  }
  a {
    color: black;
  }
  a:hover {
    text-decoration: none;
    color: black;
  }
  label {
    color: black;
  }
  #id_profile_image {
    opacity: 0;
    position: absolute;
    z-index: -1;
  }
</style>
<form method="POST" class="text-center" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container">
    <div class="container-fluid justify-content-center">
      <div class="neuraltrain">
        <h1>Edit profile</h1>
      </div>
    </div>
    <div class="user_details">
      <div class="form-floating mb-3">
        <input
          type="email"
          name="email"
          value="{{request.user.email}}"
          maxlength="60"
          required=""
          id="id_email"
          class="form__input"
        />
      </div>
      <div class="form-floating mb-3">
        <input
          type="text"
          name="username"
          value="{{request.user.username}}"
          maxlength="30"
          required=""
          id="id_username"
          id="username"
          class="form__input"
        />
      </div>
      <input
        type="file"
        name="profile_image"
        accept="image/*"
        id="id_profile_image"
      />
      <div class="submit_picture">
        <label class="btn" for="id_profile_image"
          ><svg
            xmlns="http://www.w3.org/2000/svg"
            width="70"
            height="70"
            fill="currentColor"
            class="bi bi-person-circle"
            viewBox="0 0 16 16"
          >
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
            <path
              fill-rule="evenodd"
              d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"
            /></svg
        ></label>
      </div>
    </div>
    <br />
    <button action="" type="submit" class="btn primary">Save changes</button>
  </div>
</form>
{% endblock %}

accounts/templates/leaderboard.html
{% extends 'base.html' %} {% block content %}
<style>
  * {
    font-family: "Rubik", sans-serif;
  }
  a {
    color: black;
  }
  a:hover {
    text-decoration: none;
    color: black;
  }

  body {
    background: linear-gradient(-45deg, #00fff2, #2a62ff, #973dfd, #ffc400);
    background-size: 300% 300%;
    animation: gradient 8s ease infinite;
    display: flex;
    align-items: center;
  }

  @keyframes gradient {
    0% {
      background-position: 0% 50%;
    }
    50% {
      background-position: 60% 10%;
    }
    100% {
      background-position: 0% 50%;
    }
  }

  .content-table {
    border-collapse: collapse;
    margin: 30px 0;
    font-size: 0.9em;
    min-width: 400px;
    border-radius: 5px;
    overflow: hidden;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
  }

  .content-table tr {
    background-color: #ffffff;
    text-align: left;
    font-weight: bold;
  }

  .content-table th,
  .content-table td {
    border: none;
    padding: 12px 15px;
  }

  .content-table tbody tr {
    border-bottom: 1px solid #dddddd;
  }

  .content-table tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
  }

  .content-table tbody tr.active-row {
    font-weight: bold;
    color: #009879;
  }

  h1 {
    color: white;
  }
</style>
<div align="center">
  <h1 class="text-center">Leaderboard</h1>
  <table class="content-table">
    <tr style="background-color: #973dfd; color: white">
      <div>
        <th>username</th>
        <th>profile picture</th>
        <th>last login</th>
        <th>coins</th>
        <th>followers</th>
        <th>following</th>
      </div>
    </tr>
    {% for user in users %}
    <tr>
      <td><a href="{% url 'profile' user.username %}">{{user.username}}</a></td>
      <td>
        <a href="{% url 'profile' user.username %}">
          <img
            src="{{user.profile_image.url}}"
            class="img-circle article-img"
            alt=""
            style="width: 4rem"
          />
        </a>
      </td>
      <td>{{user.last_login}}</td>
      <td>{{user.coins}}</td>
      <td>{{user.followers.count}}</td>
      <td>{{user.following.count}}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

accounts/templates/submit_post.html
{% extends 'base.html' %} {% block content %}
<style>
  * {
    font-family: "Rubik", sans-serif;
  }
  a {
    color: black;
  }

  a:hover {
    text-decoration: none;
    color: black;
  }

  i {
    font-size: 2em;
    float: left;
    margin-left: 2%;
  }
  body {
    background: linear-gradient(-45deg, #00fff2, #2a62ff, #973dfd, #ffc400);
    background-color: #e6e6e6;
    background-size: 400% 400%;
    animation: gradient 8s ease infinite;
    display: flex;
    align-items: center;
  }
  .container {
    max-width: 700px;
    width: min(500px, 70%);
    background: #fff;
    padding: 25px 30px;
    border-radius: 5px;
    margin-top: 100px;
  }
  .form__input {
    font-family: "Rubik", sans-serif;
    padding-bottom: 1px;
    padding-right: 50px;
    padding-left: 5px;
    background-color: rgb(243, 243, 243);
    font-size: 15px;
    border-color: rgb(251, 252, 252);
    border: 1px;
    border-radius: 2px;
    margin-bottom: 10px;
    display: flex;
    flex: 1;
    width: 100%;
  }

  .submit_picture {
    margin-bottom: 0px;
    padding: 0%;
  }

  @keyframes gradient {
    0% {
      background-position: 0% 50%;
    }
    50% {
      background-position: 80% 40%;
    }
    100% {
      background-position: 0% 50%;
    }
  }

  h1 {
    color: black;
    display: flex;
  }

  .neuraltrain {
    font-family: "Rubik", sans-serif;
  }

  h3 {
    color: black;
  }
  h4 {
    color: black;
  }
  a {
    color: black;
  }
  a:hover {
    text-decoration: none;
    color: black;
  }
  label {
    color: black;
  }
  #id_profile_image {
    opacity: 0;
    position: absolute;
    z-index: -1;
  }

  .bi.bi-question-circle {
    cursor: pointer;
  }

  .bi.bi-heart {
    cursor: pointer;
  }
  .button {
    height: 45px;
    margin: 45px 0;
    margin-top: 2px;
    /* transition:0.5s all; */
    /* background: linear-gradient(-45deg, #00adb3, #0052e9, #001f58); */
    border-radius: 5px;
    cursor: pointer;
    background-color: #973dfd;
  }
  .button {
    height: 100%;
    width: 100%;
    outline: none;
    color: #fff;
    border: none;
    font-size: 500;
    font-weight: 500;
    letter-spacing: 1px;
    margin-top: 0%;
    border-radius: 5px;
  }

  .form-floating.mb-3 {
    display: flex;
    text-align: center;
  }

  #id_post_image {
    opacity: 0;
    position: absolute;
    z-index: -1;
  }
</style>
<div class="container">
  <div class="container-fluid justify-content-center">
    <h1>Post</h1>
  </div>
  <div class="user_details">
    <form method="POST" action="" enctype="multipart/form-data">
      {% csrf_token %}

      <!-- {% for field in post_form %}
			<div class="form-floating mb-3">
				{{ field.errors }}
					{{ field }}
			</div>
		{% endfor %} -->
      <div class="form-floating mb-3">
        <input
          type="text"
          name="caption"
          maxlength="60"
          autofocus
          required
          id="id_caption"
          id="caption"
          class="form__input"
          placeholder="caption"
        />
      </div>
      <div class="form-floating mb-3">
        <input
          type="file"
          name="image"
          required
          id="image"
          id="id_post_image"
          class="form__input"
        />
      </div>
      <div class="form-floating mb-3">
        <input
          type="text"
          name="question"
          maxlength="30"
          required
          id="id_question"
          id="question"
          class="form__input"
          placeholder="question"
        />
      </div>
      <div class="form-floating mb-3">
        <input
          type="text"
          name="option1"
          maxlength="30"
          required
          id="id_option1"
          id="option1"
          class="form__input"
          placeholder="option 1"
        />
      </div>
      <div class="form-floating mb-3">
        <input
          type="text"
          name="option2"
          maxlength="30"
          required
          id="id_option2"
          id="option2"
          class="form__input"
          placeholder="option 2"
        />
      </div>
      <div class="form-floating mb-3">
        <input
          type="text"
          name="option3"
          maxlength="30"
          id="id_option3"
          id="option3"
          class="form__input"
          placeholder="option 3"
        />
      </div>
      <div class="form-floating mb-3">
        <input
          type="text"
          name="correct_answer"
          maxlength="30"
          required
          id="id_correct_answer"
          id="username"
          class="form__input"
          placeholder="correct answer"
        />
      </div>
      <input type="submit" name="Register" class="button" value="Post    " />
    </form>
  </div>
</div>
{% endblock %}