accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("logout/", views.logout_view, name="logout"),
    path("login/", views.login_view, name="login"),
    path("register/", views.registration_view, name="register"),
    path("leaderboard/", views.leaderboard_view, name="leaderboard"),
    path("<str:username>/follow/", views.follow_view, name="follow"),
]

chats/urls.py
# chats/urls.py
from django.urls import path

from . import views

app_name = "chats"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("room/", views.room, name="room"),
]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from accounts.views import home
from chats import views
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import (
    profile_view,
    like_view,
    quiz_score_view,
    user_enter_quiz,
    edit_profile_view,
    delete_post_view,
    quiz_view,
    post_comment,
    clear_view,
    submit_post_view,
    # search_bar,
    drop_box,
)

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("", home, name="home"),
    path("", include("accounts.urls")),
    path("", include("chats.urls")),
    path("<str:username>/", profile_view, name="profile"),
    path("<str:username>/edit_profile/", edit_profile_view, name="edit_profile"),
    path("like", like_view, name="like"),
    path("post_comment", post_comment, name="post_comment"),
    path("quiz", quiz_view, name="quiz_view"),
    path("quiz_score", quiz_score_view, name="quiz_score"),
    path("user_enter_quiz", user_enter_quiz, name="user_enter_quiz"),
    path("<str:post_id>/delete/", delete_post_view, name="delete"),
    path("<str:post_id>/clear/", clear_view, name="clear"),
    path("submit_post", submit_post_view, name="submit_post"),
    # path("search_bar", search_bar, name="search_bar"),
    path("drop_box", drop_box, name="drop_box"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&family=Roboto+Slab&family=Rubik:ital@1&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
    />

    <link
      rel="icon"
      href="https://img.search.brave.com/oH4k6o-8bLPxjRCs5rHfYcUTEe5W6QW5pasq2RkFxo4/rs:fit:1200:1200:1/g:ce/aHR0cHM6Ly93d3cu/dW5pdmVyc2V0b2Rh/eS5jb20vd3AtY29u/dGVudC91cGxvYWRz/LzIwMjAvMDIvQXJp/c3RvdGxlX0FsdGVt/cHNfSW52ODU3NS5q/cGc"
    />

    <script src="https://unpkg.com/@solana/web3.js@latest/lib/index.iife.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Neuraltrain</title>
    <style>
      * {
        border: 0;
        padding: 0;
        margin: 0;
      }
      table,
      th,
      td {
        border: 1px solid black;
      }

      i {
        color: #973dfd;
      }
      i:hover {
        color: #c28cff;
      }

      img {
        width: 100%;
        max-height: 100%;
      }

      .img-circle {
        clip-path: circle();
      }

      .navbar {
        position: fixed;
        top: 0px;
      }

      #navbar {
        background-color: rgb(255, 255, 255);
        
      }

      nav {
        
        display: block;
        margin: 0;
        padding: 10px;
        position: fixed;
        left: 0;
        right: 0;
        box-shadow: 0 3px 4px 0 rgba(0, 0, 0, 0.2);
        max-height: 65px;
      }

      .search-input .autocomplete-box {
        padding: 0;
        opacity: 0;
        pointer-events: none;
        max-height: 220px;
        height: auto;
        overflow-y: auto;
        position: fixed;
        background-color: #efefef;
        width: 208px;
      }

      .search-input.active .autocomplete-box {
        padding: 3px 8px;
        margin-top: 10px;
        opacity: 1;
        pointer-events: auto;
        border-radius: 5px;
      }
      .autocomplete-box li {
        list-style: none;
        padding: 2px 8px;
        display: none;
        width: 100%;
        cursor: pointer;
        border-radius: 5px;
      }
      .search-input.active .autocomplete-box li {
        display: block;
      }
      .autocomplete-box li:hover {
        background: #efefef;
      }
      body {
        /* background: linear-gradient(-45deg, #e6592e, #d2d5dd, #2642dd, #e2b221); */
        background-color:#0c0c0c;
        /* background-size: 200% 200%; */
        /* animation: gradient 8s ease infinite; */
        display: flex;
        height: 100vh;
        align-items: center;
      }

      /* Blue and Green */

      .search_data {
        box-sizing: border-box;
        height: 40%;
        width: 100%;
        border-radius: 8px;
        border-color: white;
        border-style: none;
        background-color: #f1eded;

        margin-top: 5px;
        padding-top: 6px;
        padding-bottom: 6px;
        padding-left: 10px;
        

        padding-right: 10px;
        outline: none;
        text-justify: auto;
       
        
      }
    </style>
  </head>
  <script
    type="module"
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"
  ></script>
  <body>
    <div style="width: 1000px; margin: auto">
      <div id="navbar" class="justify-content">
      {% if request.user.is_authenticated %}
        <nav style="height: fit-content" id="navbar" class="navbar">
          <a class="nav-link disabled" href="{% url 'submit_post' %}">
            <i class="bi bi-plus-circle" style="font-size: 1.7rem; margin-left: 180px;"></i>
          </a>
          <a class="nav-link disabled" href="{% url 'home' %}">
            <i id="home" class="bi bi-house" style="font-size: 1.7rem"></i>
          </a>
          <a class="nav-link disabled" href="{% url 'chats:room' %}">
            <i class="bi bi-chat" style="font-size: 1.7rem"></i>
          </a>
          <a
            class="nav-link disabled"
            aria-current="page"
            href="{% url 'accounts:leaderboard' %}"
          >
            <i class="bi bi-bar-chart" style="font-size: 1.7rem"></i>
          </a>
          <a class="nav-link disabled" href="{% url 'profile' user.username %}">
            <img
              src="{{user.profile_image.url}}"
              class="img-circle"
              alt=""
              style="width: 2.5rem"
            />
          </a>
          {% if user.is_superuser %}
          <a
            class="nav-link disabled"
            href="{% url 'admin:index' %}"
            target="_blank"
          >
            <i class="bi bi-file-earmark-lock2" style="font-size: 1.7rem"></i>
          </a>
          {% endif %}

          <div class="search-input" id="search-input">
            <input
              autocomplete="off"
              type="search"
              id="search_data"
              class="search_data"
              placeholder="Search"
            />
            <div class="autocomplete-box" id="autocomplete-box"></div>
          </div>

          <a class="nav-link disabled" href="{% url 'accounts:logout' %}">
            <i class="bi bi-door-open" style="font-size: 1.7rem"></i>
          </a>
          {% else %}
          <div class="curve"></div>
          {% endif %}
        </div>
      </nav>
      <div style="margin-top: 10%"></div>
      {% block content %} {% endblock %}
    </div>
  </body>
  <script>
    const searchWrapper = document.getElementById("search-input");
    const inputBox = document.getElementById("search_data");
    const suggBox = document.getElementById("autocomplete-box");

    document.getElementById("search_data").addEventListener("click", loadData);
    function loadData(e) {
      $.ajax({
        url: "{% url 'drop_box' %}",
        type: "POST",
        data: { csrfmiddlewaretoken: "{{ csrf_token }}" },
        dataType: "json",
        success: function (json) {
          let suggestions = json.users;

          inputBox.onkeyup = (e) => {
            let userData = e.target.value;
            let emptyArray = [];
            if (userData) {
              emptyArray = suggestions.filter((data) => {
                return data
                  .toLocaleLowerCase()
                  .startsWith(userData.toLocaleLowerCase());
              });
              emptyArray = emptyArray.map((data) => {
                // passing return data inside li tag
                return (data = `<li ><a id="first_url" href="http://200.88.178.71:5003/${data}/" >${data}</a></li>`);
              });
              searchWrapper.classList.add("active"); //show autocomplete box
              showSuggestions(emptyArray);
              let allList = suggBox.querySelectorAll("li");
              for (let i = 0; i <= script.allList.length; i++) {
                //adding onclick attribute in all li tag
                allList[i].setAttribute("onclick", "select(this)");
              }
            } else {
              searchWrapper.classList.remove("active"); //hide autocomplete box
            }
          };
          function showSuggestions(list) {
            let listData;
            if (!list.length) {
              userValue = inputBox.value;
              listData = `<li><a id="first_url" href="http://200.88.178.71:5003/${userValue}/" >${userValue}</a></li>`;
            } else {
              listData = list.join("");
            }
           
            suggBox.innerHTML = listData;
          }
        },
      });
    }
    document.getElementById("search_data").onkeypress = function (e) {
      if (!e) e = window.event;
      var keyCode = e.code || e.key;
      if (keyCode == "Enter") {
        let url = document.getElementById("first_url").href;
        window.location.replace(url);
        return false;
      }
    };
  </script>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<style>
	* {
    	font-family: "Rubik", sans-serif;
  	}
	a {
		color: black;
	}
	a:hover {
		text-decoration: none;
		color: black;
	}
    .modal-container {
        background-color: rgba(0, 0, 0, 0.2);
        position: fixed;
        top: 0;
        left: 0;
        height: 100vh;
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        opacity: 0;
        pointer-events: none;
    }
    .modal-container.show {
        opacity: 1;
        pointer-events: auto;

    }
    .quiz-modal {
        background-color: rgb(255, 255, 255);
        width: 600px;
        max-width: 100%;
        padding: 30px 50px;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    }
    .quiz-modal h1 {
        margin: 0;
    }

    .quiz-modal p {
        font-size: 14px;
        opacity: 0.7;
    }

	i {
		font-size: 2em;
		float: left;
		margin-left: 2%;
		cursor: pointer;
	}
    body {
    /* background: linear-gradient(-45deg, #00adb3, #0034a3, #00163f); */
    background: linear-gradient(-45deg, #00fff2, #2a62ff, #973dfd, #ffc400);
    background-size: 150% 150%;
    animation: gradient 8s ease infinite;
    display: flex;
    align-items: center;
  }

  @keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
    50% {
        background-position: 80% 40%;
    }
    100% {
        background-position: 0% 50%;
    }
  }
  a {
    color:black;
  }
  a:hover {
    text-decoration: none;
    color: black;
  }
  .container{
	padding-top: 10px ;
	height: 75px;
    background: #fff;
    border-radius: 5px;
    min-height: 100%;
	width: 50%;
    height: 50%;
	padding-bottom: 3px;
  }
img {
    max-width: 100%;
    max-height: 100%;
	}


	.comments-container {
        background-color: rgba(0, 0, 0, 0.2);
        position: fixed;
        top: 0;
        left: 0;
        height: 100vh;
        width: 100vw;
        display: flex;
        align-items: center;
        justify-content: center;
        opacity: 0;
        pointer-events: none;
    }
    .comments-container.show {
        opacity: 1;
        pointer-events: auto;

    }

	.comments-modal {
        background-color: rgb(255, 255, 255);
        width: 600px;
        max-width: 100%;
        padding: 30px 50px;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    }
	.btn.primary {
		margin-top: 15px;
	}

	.author-caption {
		margin-top: -25px;
	}


	
</style>
{% if user.is_authenticated %}
<div style="margin-top: 14%"></div>
	{% for post in all_posts %}
<div>
	<div style="margin-top: 40px;" class="container">
		<div>
			<div>
				<div>
					<div>
						<div style="line-height: 100%;">
							<a href="{% url 'profile' post.author.username %}">
								<img style='width: 2.5rem;' src="{{post.author.profile_image.url}}" class="rounded-circle article-img">
								@{{post.author.username}}
							</a>
						</div>
					</div>
				</div>
				<br>
				{% if post.image %}
				<img src="{{ post.image.url }}" width="350" height="400">
				<div style='margin-left: 2%'>
					<div>
						<form action="{% url 'like' %}" method='POST'>
						{% csrf_token %}
						<div>
							{% if request.user in post.likes.all %}
							<i id='like {{post.id}}' style="float: left;" class="bi bi-heart-fill" style="font-size: 4rem"></i>
							{% else %}
							<i id='like {{post.id}}' style="float: left;" class="bi bi-heart" style="font-size: 4rem"></i>
							{% endif %}
						</div>
					</form>
					{% if post.author != request.user %}
					{% if user not in post.users_did_quiz.all %}
					<div id="user_did_quiz{{post.id}}">
						<i class="bi bi-question-circle" id="open_quiz{{post.id}}" value="{{post.id}}" name="{{post.id}}"></i>
					</div>
					{% else %}
					<div id="quiz_completed">
						{% if user in post.users_right.all %}
						<i id="completed_button" style="color:rgb(83, 199, 83)" class="bi bi-check-circle"></i>
						{% else %}
						<i id="completed_button" style="color:rgb(243, 66, 66)" class="bi bi-x-circle"></i>
						{% endif %}
					</div>
					{% endif%}
					{% endif %}
					<!-- <p>{{post.users_did_quiz.count}} users already did the quiz</p> -->
					<div class="modal-container" id="modal_container{{post.id}}">
						<div class="quiz-modal" id="quiz-modal{{post.id}}">
							<h1 id="quiz_question{{post.id}}">Question</h1>
							<form method="post" action="{% url 'quiz_score' %}">
								{% csrf_token %}
								
									<p id="countdown{{post.id}}"> Start Now</p>
									
										<input type="radio" id="option1_input{{post.id}}" name="quiz_option{{post.id}}"><label
											id="option1_label{{post.id}}" class="form-check-label" for="flexCheckDefault" style="margin-bottom: 5px;"></label>
											<br>
									<input type="radio" id="option2_input{{post.id}}" name="quiz_option{{post.id}}"><label
											id="option2_label{{post.id}}" class="form-check-label" for="flexCheckDefault" style="margin-bottom: 5px;"></label>
											<br>
								<input type="radio" id="option3_input{{post.id}}" name="quiz_option{{post.id}}"><label
											id="option3_label{{post.id}}" class="form-check-label" for="flexCheckDefault"></label>
							<br>
								<button class="btn primary" type="submit" name="submit{{post.id}}" value="{{post.id}}" id="submit{{post.id}}">
									Submit
								</button>
							</form>
						</div>
					</div>
						{% if post.author == request.user %}
						<a href="{% url 'delete' post.id %}">
								<i class="bi bi-trash"></i>
							</a>
							<!-- <a href="{% url 'clear' post.id %}">
								<button>
									clear all users did quiz
								</button> -->
							</a>
							{% endif %}
						</div><br>
						<div>
							<div align='left' style='margin-top: 8%;' id='total_likes{{post.id}}'>
								{{post.total_likes}} likes
							</div><br>

								<!-- <input onclick="loadComments()" type="button" value="Submit"><br>	 -->
								<!-- {% for comment in post_comments %}
								{{comment}}
								{% endfor %} -->
								<div align='left'>
									<font size='4'>
										<p>
											<div class="author-caption">
											<strong>
												<a href="{% url 'profile' post.author.username %}">
													{{post.author}}
												</a>
											</strong>
											<p style="width:100%; word-wrap: break-word;">{{post.caption}}</p>
										</div>
										</p>
									</font>
								</div>
							</div>
						</div>
						{% endif %}
					</div>
				</div>
				<script>
			document.getElementById('like {{post.id}}').addEventListener('click', loadLikes)
			function loadLikes(event) {
				$.ajax({
					url: "{% url 'like' %}",
					type: "POST",
					data: {'post_id': '{{post.id}}', 'csrfmiddlewaretoken': '{{ csrf_token }}'},
					dataType: "json",
					success: function (json) {
						document.getElementById('total_likes{{post.id}}').innerHTML = json.total_likes + ' likes';
						document.getElementById('like {{post.id}}').classList.add('bi bi-heart-fill');
					}
				})
			event.preventDefault()
			}
			document.getElementById('open_quiz{{post.id}}').addEventListener('click', openQuiz)
			function openQuiz() {
				$.ajax({
					url: "{% url 'quiz_view' %}",
					type: "POST",
					data: { "post_id": "{{post.id}}", 'csrfmiddlewaretoken': '{{ csrf_token }}' },
					dataType: "json",
					success: function (json) {
						const open = document.getElementById('open_quiz{{post.id}}');
						const modal_container = document.getElementById('modal_container{{post.id}}');
						const submit = document.getElementById('submit{{post.id}}');
						
						modal_container.classList.add("show");
						
						submit.addEventListener("click", () => {
							modal_container.classList.remove("show");
						});
						// Question
						document.getElementById("quiz_question{{post.id}}").innerHTML = json.question;
						// Option 1
						document.getElementById("option1_label{{post.id}}").innerHTML = json.option1;
						var option1_input = document.getElementById("option1_input{{post.id}}");
						option1_input.setAttribute("value", json.option1);
						// Option 2
						document.getElementById("option2_label{{post.id}}").innerHTML = json.option2;
						var option2_input = document.getElementById("option2_input{{post.id}}");
						option2_input.setAttribute("value", json.option2);
						// Option 3
						document.getElementById("option3_label{{post.id}}").innerHTML = json.option3;
						var option3_input = document.getElementById("option3_input{{post.id}}");
						option3_input.setAttribute("value", json.option3);
						
						setInterval(updateCountdown, 1000);
						let seconds = 10;
						function updateCountdown() {
							document.getElementById("countdown{{post.id}}").innerHTML = seconds;
							seconds--;
						}
						$.ajax({
							type: "POST",
							url: "{% url 'user_enter_quiz' %}",
							data: { "post_id": "{{post.id}}", 'csrfmiddlewaretoken': '{{ csrf_token }}' },
							dataType: "json",
							success: function (json) {
							}
						})
						setTimeout(submitModal, 11000);
						function submitModal() {
							modal_container.classList.remove("show");
							try {
								quiz_option = document.querySelector('input[name = "quiz_option{{post.id}}"]:checked').value;
							} catch {
								quiz_option = null
							}
							$.ajax({
								type: "POST",
								url: "{% url 'quiz_score' %}",
								data: { "post_id": "{{post.id}}", 'csrfmiddlewaretoken': '{{ csrf_token }}', "quiz_option": quiz_option},
								dataType: "json",
								success: function (json) {
									if (json.user_right == true) {
									const situation = '<i id="completed_button" style="color:rgb(83, 199, 83)" class="bi bi-check-circle"></i>'
									document.getElementById('user_did_quiz{{post.id}}').innerHTML = situation;
									
								} else {
									const situation = '<i id="completed_button" style="color:rgb(243, 66, 66)" class="bi bi-x-circle"></i>'
									document.getElementById('user_did_quiz{{post.id}}').innerHTML = situation;	
								}
								
								}
							})
						event.preventDefault()
					}
					document.getElementById('submit{{post.id}}').addEventListener('click', loadScore)
					function loadScore() {
						var quiz_option = document.querySelector('input[name = "quiz_option{{post.id}}"]:checked').value;	
						$.ajax({
							type: "POST",
							url: "{% url 'quiz_score' %}",
							data: { "post_id": "{{post.id}}", 'csrfmiddlewaretoken': '{{ csrf_token }}', "quiz_option": quiz_option },
							dataType: "json",
							success: function (json) {
								if (json.user_right == true) {
									const situation = '<i id="completed_button" style="color:rgb(83, 199, 83)" class="bi bi-check-circle"></i>'
									document.getElementById('user_did_quiz{{post.id}}').innerHTML = situation;
									
								} else {
									const situation = '<i id="completed_button" style="color:rgb(243, 66, 66)" class="bi bi-x-circle"></i>'
									document.getElementById('user_did_quiz{{post.id}}').innerHTML = situation;	
								}
								}
							})
						event.preventDefault()
					}
				}
			})
		}
		</script>

		<script>
			document.getElementById("comment{{post.id}}").addEventListener("click", loadComments) 

				function loadComments() {

								const comments_container = document.getElementById('comments_container{{post.id}}');
								
								const close_comments_container = document.getElementById('close_comments{{post.id}}');
								comments_container.classList.add("show");
								close_comments_container.addEventListener("click", () => { comments_container.classList.remove("show");});
							}

							
			document.getElementById("post_comment{{post.id}}").addEventListener("click", postComment)
			console.log("bien")
			function postComment(e) {
				
				let comment = document.getElementById("input_comment{{post.id}}").value
				console.log(comment)

				$.ajax({
							type: "POST",
							url: "{% url 'post_comment' %}",
							data: { "post_id": "{{post.id}}", 'csrfmiddlewaretoken': '{{ csrf_token }}', "comment": comment},
							dataType: "json",
							success: function (json) {
								console.log("GG")


			}
			

		})
		event.preventDefault()
	}
			

			
		</script>
	</div>
</div>
{% endfor %}
{% endif %}
{% endblock %}